#include "verify.h"

#include "include.h"

void print_error(uint32_t position) {
    printf(RED  "                             ...'''...\n"
                "                        ..,:loxxkkOOkkxo:,.\n"
                "                     ..;:loddxxkOO00KKKKK0Od:.\n"
                "                    .,;:looddkkO000KKKKXXXXXKOo,.\n"
                "                  ..',;codxxkkO000000KKXXXNNNXKOo.\n"
                "                 ..',;:loxxkkkkO000000KXNWNNXX000d'\n"
                "                ...,;;:coddxxxxkOO0OO00KXNNNXK0OOOc.\n"
                "                ...,;;;:cloddddkO000000KXNNNXK0OO0d.\n"
                "                ''.',;::clodxkkOOOO000KXNNWNXX0O0XO,\n"
                "                ','';;;;;;;:ldkOkOOOOkxxxOKXXX0OKX0:\n"
                "                ';;,,,'.....',:lldkkko,''';:oxOKXKO:\n"
                "                .;,'..     ..,,:dkO0O;.  ....'ckKKk,\n"
                "                .',;'.      .,;l0NNXO:.  ...''ckOOo.\n"
                "                .';cc'.    ..,:ldkO00kl;....':x00k;\n"
                "                 .;coc'....',;,.. .:OXXKOdlcokKK0k;\n"
                "                .';;:cc:;,;:c;..   .oK0xoooddkOOkd'\n"
                "                 .','''''',;c'..    ,OKx:'..':ooc.\n"
                "                   .....',,;c;.... .:0XOl,.  ...\n"
                "                         .;;:c:;cdkk0X0xo'\n"
                "                         .,;clc;:xO0KK0d;.\n"
                "                         .'''......',,,.\n"
                "                          ...\n"
                " ___  _  _  _  _  ____   __    _  _    ____  ____  ____  _____  ____\n"
                "/ __)( \\/ )( \\( )(_  _) /__\\  ( \\/ )  ( ___)(  _ \\(  _ \\(  _  )(  _ \\\n"
                "\\__ \\ \\  /  )  (   )(  /(__)\\  )  (    )__)  )   / )   / )(_)(  )   /\n"
                "(___/ (__) (_)\\_) (__)(__)(__)(_/\\_)  (____)(_)\\_)(_)\\_)(_____)(_)\\_)\n"
                "=========================================================================\n"
                "                          AT POSITION:%u\n"
                "=========================================================================\n"
                RESET, position);
}
